### PR TITLE
Make groups claim optional

### LINKED ISSUE #129: Requiring the 'groups' claims is too restrictive
I have just seen a user reporting that the MP-JWT runtime fails to validate Auth0 tokens. I think it is a major barrier to the wider adoption of MP JWT given that many popular OIDC providers will not be able to include the `groups`claim.
IMHO the 'group' claim should be treated somehow similarly to the (required) `upn` claim. For example, one option could be for the MP JWT implementation to default to 'Default' groups or some other default value.
Rejecting the otherwise perfectly valid tokens used in the productions to secure the services is too restrictive

### PR DESCRIPTION
**Pull request by sberyozkin**
This PR updates `interoperability` document and adds a simple test (`PermitAll` is really equivalent to requiring no RBAC).

Fixes #129.

CC @radcortez, Roberto, not sure why I can't request a review from you, probably need to update some permissions

### CODE REVIEW

**Comment by sberyozkin** [comment]
@rdebusscher FYI, I've moved the text to do with the `aud` injection hint here, immediately under `Claims` description as part of this PR. Perhaps it will be better here. Also update `JsonWebToken` description

File: tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java [hunk 1]
```diff
@@ -143,6 +143,24 @@ public void callEcho() throws Exception {
         Assert.assertEquals(reply, "hello, user=jdoe@example.com");
     }
 
+    @RunAsClient
+    @Test(groups = TEST_GROUP_JAXRS,
+        description = "Validate a request with MP-JWT without a groups claim succeeds with HTTP_OK}")
+    public void callEchoNoGroups() throws Exception {
+        Reporter.log("callEcho, expect HTTP_OK");
```
Comment (sberyozkin) [inline tck/src/test/java/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java:150]: Oops, I need to fix it, sorry, I thought I did

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 2]
```diff
@@ -33,11 +33,11 @@ To meet those requirements, we introduce 2 new claims to the MP-JWT:
 
 * "upn": A human readable claim that uniquely identifies the subject or user principal of the token, across
 the MicroProfile services the token will be accessed with.
-* "groups": The token subject's group memberships that will be mapped to Java EE style application
-level roles in the MicroProfile service container.
+* "groups": A list of group names that have been assigned to the principal of the MP-JWT. This typically will require a mapping at the application container level to application deployment roles, but a one-to-one between group names and application role names is required to be performed in addition to any other mapping when this claim is available in the token.
```
Comment (radcortez) [inline spec/src/main/asciidoc/interoperability.asciidoc:36]: Maybe change `that have been assigned` to `to be assigned`?

Change `application deployment roles` to just `application roles`.

**Comment by radcortez** [comment]
No worries. I think I don't have permissions yet. I know that my committer status was approved, but not sure how long it takes for the process to finish.

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 2 above)
Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: @radcortez This is the original spec text. I'm assuming `have been assigned` means that these groups have already been allocated to a given client/user somewhere in the OIDC admin console (ex Keycloak) and next - they may need to be mapped to the deployment specific roles.
 
`application deployment roles` -> `application roles` - fine with me

Comment (radcortez) [reply spec/src/main/asciidoc/interoperability.asciidoc]: I interpret that as the token containing the `groups` and being used to produce the `Principal`. Because `groups` already exist in the token before the `Principal` I think it would be more clear as a future action `to be assigned`.

I guess it is only semantics :) I'm fine either way.

Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc]: Sure, I've no problems really too, so will update

**Comment by sberyozkin** [comment]
@rdebusscher, others, any comments on your end ? I'll be happy to go with Roberto's comments otherwise, even though I can't technically assign him as a reviewer yet.
Thanks

**Comment by sberyozkin** [comment]
I'd like to follow up with the clarification around few other claims immediately after this PR

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 3]
```diff
@@ -33,11 +33,11 @@ To meet those requirements, we introduce 2 new claims to the MP-JWT:
 
 * "upn": A human readable claim that uniquely identifies the subject or user principal of the token, across
 the MicroProfile services the token will be accessed with.
-* "groups": The token subject's group memberships that will be mapped to Java EE style application
-level roles in the MicroProfile service container.
+* "groups": A list of group names to be assigned to the principal of the MP-JWT. This typically will require a mapping at the application container level to application roles, but a one-to-one between group names and application role names is required to be performed in addition to any other mapping when this claim is available in the token.
```
Comment (rdebusscher) [inline spec/src/main/asciidoc/interoperability.asciidoc:36]: Last part can be confusing because we basically say "Some other mapping is **required** on the group names". but we do not specify what that means. But use the word **required**.

I guess we want to leave the option open that the runtime performs any custom mapping on the group names which are configured (implementation specific)

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 4]
```diff
@@ -61,11 +61,8 @@ upn:: This MP-JWT custom claim is the user principal name in the java.security.P
     principal name in javax.security.enterprise.identitystore.IdentityStore. If this claim is missing, fallback to
     the http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims["preferred_username", OIDC Section 5.1] should be
     attempted, and if that claim is missing, fallback to the "sub" claim should be used.
-groups:: This MP-JWT custom claim is the list of group names that have been assigned to the principal of the MP-JWT.
-    This typically will required a mapping at the application container level to application deployment roles, but a
-    one-to-one between group names and application role names is required to be performed in addition to any
-    other mapping.
 
+[NOTE] It is recommended that JWT tokens contain a `groups` claim if the endpoint requires Authorization. Tokens without this claim can be accepted if the endpoint requires Authentication only. Support for mapping the groups from other claims is optional.
```
Comment (rdebusscher) [inline spec/src/main/asciidoc/interoperability.asciidoc:65]: Shouldn't we introduce the mapper SPI or the configuration that the groups can be taken from another claim here also.

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 5]
```diff
@@ -381,12 +391,12 @@ The MP-JWT specification requires that an MP-JWT implementation reject a bearer
 invalid MP-JWT token if any of the following conditions are not met:
 
 1. The JWT must have a JOSE header that indicates the token was signed using the RS256 algorithm.
-2. The JWT must have an iss claim representing the token issuer that maps to an MP-JWT implementation
-container runtime configured value. Any issuer other than those issuers that have been whitelisted
-by the container configuration must be rejected with an HTTP_UNUATHENTICATED(401) error.
-3. The JWT signer must have a public key that maps to an MP-JWT implementation container runtime
+2. The JWT signer must have a public key that maps to an MP-JWT implementation container runtime
```
Comment (rdebusscher) [inline spec/src/main/asciidoc/interoperability.asciidoc:394]: `JWT signer` is not a good term as we are not signing a token here but verifying it.

JWT Signature verifier?

Or what exactly we do want to tell the people here?  When a key identification (kid then) is encountered which is not expected we need to return 401?

Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:394]: @rdebusscher I've just moved the existing lines around there, the whole `interoperability.doc` needs a good refresh but `JWT Signature verifier` is minor but a good start. I believe `kid` is mentioned elsewhere in scope of the JWK format text, this is just a high level requirement that a public key should be available.

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 4 above)
Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:65]: @rdebusscher #94 was opened awhile back, but I've marked it now for JWT 2.0. I'd like to release `1.2` asap so that we can go ahead with breaking things and try to make it for MP 4.0 with MP JWT 2.0. This is why I'm postponing everything that can be postponed including the builder API, even though it does not break anything. The only other minor improvement I'd like to try to squeeze is the ES256 support in order to ensure that when the builder api arrives at some point it will be synced (as per your earlier comments) with the server side support.
So, it was a long way to suggest to address the mapper spi post 1.2 :-)

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 5 above)
Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:394]: @rdebusscher I've read that text and it just requires that a signer which signs (with a private key) should have a matching public key that can be mapped by MP JWT server somehow. We cam tweak for sure, but I'd rather have a dedicated issue (Improve/clarify the texts etc) as it can easily take few days :-)

**Comment by sberyozkin** [comment]
@rdebusscher I've resolved 2 comments (please reopen if preferred) and kept one open - please check the updated text - I've updated it to make it obvious MP JWT implementations can provide the custom mappers and mentioned these mappers will be supported formally in the future versions

**Comment by sberyozkin** [comment]
@rdebusscher I've lifted the change request here as well in preparation for a merge. As said in the other PR, I will hold off till Fri and we can always review/reopen before 1.2 is out

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 3 above)
Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: @rdebusscher I've added a note below that the custom mapping is possible. The above just says that of no mapping is done then the groups values are taken as is.

Comment (rdebusscher) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: I still find it confusing (the one-to-one mapping AND any other mapping is required). But everyone else if fine with this, you can merge it.

Proposal 

>This typically will require a mapping at the application container level to application roles, a one-to-one between group names and application role names is the default when no custom mapping is defined in an implementation specific way.

**Comment by sberyozkin** [comment]
@rdebusscher Sure, Let me tweak it and I'll ping you once it is ready

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 6]
```diff
@@ -33,10 +33,10 @@ To meet those requirements, we introduce 2 new claims to the MP-JWT:
 
 * "upn": A human readable claim that uniquely identifies the subject or user principal of the token, across
 the MicroProfile services the token will be accessed with.
-* "groups": The token subject's group memberships that will be mapped to Java EE style application
-level roles in the MicroProfile service container.
+* "groups": A list of group names to be assigned to the principal of the MP-JWT. This typically will require a mapping at the application container level to application roles. A one-to-one mapping between group names and application role names is done by default when no custom mapping is defined in an implementation specific way.
```
Comment (sberyozkin) [inline spec/src/main/asciidoc/interoperability.asciidoc:36]: @rdebusscher How does it look ? It does look clearer than the original text, I agree :-) CC @radcortez

Comment (Emily-Jiang) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: We should say comma separated group names.

File: spec/src/main/asciidoc/interoperability.asciidoc [hunk 7]
```diff
@@ -61,11 +61,10 @@ upn:: This MP-JWT custom claim is the user principal name in the java.security.P
     principal name in javax.security.enterprise.identitystore.IdentityStore. If this claim is missing, fallback to
     the http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims["preferred_username", OIDC Section 5.1] should be
     attempted, and if that claim is missing, fallback to the "sub" claim should be used.
-groups:: This MP-JWT custom claim is the list of group names that have been assigned to the principal of the MP-JWT.
-    This typically will require a mapping at the application container level to application deployment roles, but a
-    one-to-one between group names and application role names is required to be performed in addition to any
-    other mapping.
 
+[NOTE] It is recommended that JWT tokens have a `groups` claim if the endpoint requires Authorization but MP JWT implementations can map the groups from the other claims if the tokens have been issued by OpenId Connect and other providers which currently do not support MP JWT. Mapper SPI for extracting the groups from the custom claims will be supported in the future versions of this specification in order to make MP JWT implementations more interoperable.
```
Comment (Emily-Jiang) [inline spec/src/main/asciidoc/interoperability.asciidoc:65]: I suggest to delete "Mapper SPI for extracting the groups from the custom claims will be supported in the future versions of this specification in order to make MP JWT implementations more interoperable." as it muddles the water and no point to put some future features in the current spec as we don't have control which future version it will end up with or maybe never.

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 6 above)
Comment (rdebusscher) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: looks goods to me now.

Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:36]: @Emily-Jiang 

> We should say comma separated group names.

This will add to the confusion IMHO. `groups` claim is an array, so adding the `comma-separated` would not work well I believe. I'm not sure where commas would apply - it is an implementation specific aspect I guess. Thanks

File: spec/src/main/asciidoc/interoperability.asciidoc (hunk 7 above)
Comment (sberyozkin) [reply spec/src/main/asciidoc/interoperability.asciidoc:65]: @Emily-Jiang sounds good

**Comment by sberyozkin** [comment]
Going ahead with the merge now - any concerns - please open new issues. Thanks all
